### ISSUE TITLE
Image aspect ratio

### ISSUE THREAD

**Issue by reynico** [artlav/meteor_decoder#9]
Hi!

I noticed most of the decoded pictures seems to be a little narrow such as http://weather.reyni.co/image/2020/02/10/METEOR-M220200210-081615-122.jpg, that should be something like http://weather.reyni.co/image/2020/02/10/METEOR-M220200210-081615-122-adjust.jpg (20% wider here, give or take)

I'm running `medet_arm` as follows:

* `medet_arm "meteor.qpsk" "meteor" -cd`
* `medet_arm "meteor.dec" "meteor-img" -r 65 -g 65 -b 64 -d`

Is there anything I can do to know how much wider the image needs to be?

**Comment by pfranchini** [comment]
You need to rectify the curvature of the image

https://github.com/dbdexter-dev/meteor_rectify

**Comment by reynico** [comment]
Thank you!
